name = "led_tasking_fk723m1_demo"
description = "A0B LED Blink Tasking Demo for FK723M1 Board"
version = "0.1.0"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]

executables = ["led_tasking_fk723m1_demo"]
project-files = ["gnat/led_tasking_fk723m1_demo.gpr"]

[[depends-on]]
a0b_tasking_armv7m = "*"
light_fk723m1_zgt6 = "*"
[[pins]]
a0b_tasking_armv7m = { path='../..' }
